### PR TITLE
chore: improvements to create a shortcuts management system

### PR DESCRIPTION
**Pull request by dubisdev**
Edit: I'll continue with this in another PR to keep this PR atomic

For now, I started refactoring some part related to the shortcuts so the codebase can be better understanded.

## To-dos
- [x] Allow the user to input a shortcut (a5e2b1e)

In a future PR will be included

- [ ] Tauri: add a way to manage (add, remove, update) shortcuts
- [ ] Electron: add a way to manage (add, remove, update) shortcuts

### Related issues
re #403 
re #74 

Also found a bug with the Undo - Redo shortcut (4a61aa0). It was using the casing of the 'z' character to determine when it should be one or the other. This caused that, if the "Mayus" was activated, doing `ctrl + Z` triggered the redo.

Now the shortcuts are:

- `ctrl + z` to undo
- `ctrl + shift + z` to redo 

Discord discussion: https://discord.com/channels/1173649313734328441/1175398470341886032

### CODE REVIEW

**Comment by dubisdev** [comment]
This should include saving the shortcuts config somewhere so we can configure the custom shortcuts on startup.

**Comment by dubisdev** [comment]
Hi @sekwah41 

I'm back with this. What do you think about renaming some of the command names? I think we can make them more descriptive.

For example:

image
image

Instead of "set_minimize" we might use "minimize_window" which I think that fits better with the things the function/commands are doing.

Other similar are: "set_show" -> "show_window", "set_close" -> "close_window"

I'm doing some small refactors to make it easier to implement the shortcuts management

**Comment by dubisdev** [comment]
Hi @sekwah41 this PR is done for now

**Comment by sekwah41** [comment]
Ill take a look after im back from visiting family :)

**Review by sekwah41 — APPROVED** [review]

**Pull request merged**
