### PR TITLE
Fix: Changing time configuration with keyboard did not work - #402

### PR DESCRIPTION
**Pull request by ziadevcom**
Hi, I fixed the #402.

I would like you to pay attention to the comments in the `ConfigSlider.tsx` in [2nd commit.](https://github.com/zidoro/pomatez/commit/c7b1056c63c12d1f302e43f039e70d858c290a93)

That is something we should fix by making another commit but I wanted to include main developers in this.

**Tested on windows portable & installer.**

https://github.com/zidoro/pomatez/assets/45315917/cba50181-61f5-4c50-ba02-1643e09df132

### CODE REVIEW

**Review by roldanjr — APPROVED** [review]

**Comment by roldanjr** [comment]
Hi, @ziadevcom kindly fix the pre-commit checks, and then I'll merge this PR. 
Please read this https://github.com/zidoro/pomatez#pencil-pre-commit. 
Thank you! 💪🏼

**Comment by ziadevcom** [comment]
@roldanjr I am not sure why it's failing.

I tried to download `pre-commit` & it gave error. It is asking me to download `Microsoft build tools`.

It's 7GB, I am working from my laptop right now because my computer fried & it's a very light weight machine. It can't afford software like that.

**Comment by sekwah41** [comment]
Im surprised its asking for that, i thought you just needed python installed.

The command to dirtily do it should be `pre-commit run --all-files`

**Comment by ziadevcom** [comment]
This does not work either. I guess there is no other option than to download 7GB of bloat that I don't need. I am really disappointed that this will be the reason for not being able to push the changes.

**Comment by roldanjr** [comment]
It's alright @ziadevcom it's just a minor thing. Maybe @sekwah41 and I will fix this later but for now I'll merge this PR :)
Thank you @ziadevcom 🙇🏼

**Comment by ziadevcom** [comment]
Thank you @roldanjr @sekwah41 

I appreciate it.

**Pull request merged**
