### PR TITLE
Pomatez v1.2.3 Hotfixes

### PR DESCRIPTION
**Pull request by roldanjr**

### CODE REVIEW

**Review by sekwah41 — COMMENTED** [review]
Ill check if the changes work fine on mac later :) Then ill approve!

**Comment by roldanjr** [comment]
https://github.com/zidoro/pomatez/pull/379#issuecomment-1551735183

**Comment by roldanjr** [comment]
Hi @sekwah41 did you try to check it on your mac? :)

**Comment by sekwah41** [comment]
Ive had to re-do the os on it as i forced the latest macos onto there Ill download it now and give it a try.

**Comment by sekwah41** [comment]
Actually ill have to do it tomorrow morning as I ran out of time

**Comment by sekwah41** [comment]
Screenshot 2023-07-01 at 23 13 20

It all seems to work pretty well, the notifications for the first time will show a generic "this will allow notifications from pomatez" so there is a chance we would want to send an initial one to get it approved by the user but its not an ongoing issue as long as they approve it so shouldn't be that much of a problem.

**Review by sekwah41 — APPROVED** [review]

**Comment by roldanjr** [comment]
Thank you @sekwah41

**Pull request merged**
