### PR TITLE
refactor(store): move old redux code to redux toolkit

### PR DESCRIPTION
**Pull request by dubisdev**
As the official docs says the `createStore` method is deprecated. This PR moves all the stores to redux-toolkit which is:

- Less verbose (also less code)
- Better supporting TypeScript
- Easier to understand

### CODE REVIEW

**Comment by dubisdev** [comment]
Hi @sekwah41 this PR is ready for now.

The new redux code for the tasks store is missing, but we can migrate it in other PR (this PR is big enought and the tasks store is more complex as it uses redux-undo).

**Comment by sekwah41** [comment]
Ill try to review this tomorrow, though will review it at least at some point next week :)

**Comment by dubisdev** [comment]
Hey @sekwah41 any news on this?

I know it's a big PR but I think it's worth it having this merged before creating another store to save the custom shortcuts settings

**Comment by sekwah41** [comment]
Sorry my bad. I should have time tomorrow but if I can I'll do it tonight.

**Review by sekwah41 — APPROVED** [review]

**Comment by sekwah41** [comment]
Tested on both the electron and tauri versions and seems fine

**Pull request merged**
